### ISSUE TITLE
Feedback and #1 Issue!

### ISSUE THREAD

**Issue by Tomato6966** [devoxin/LavaDSPX-Plugin#1]
Thank you very much for your great and kind contribution to Lavalink!
Not only your Lyrics plugin but also your Audio filter plugins works quite well.
I played around with lavadspx-plugin, fine tuned it and i'm amazed.
It replaced lavalink-filter-plugin (echo & reverb filters) and added more filters.
Thank you.

also maybe you wanna adjust these loggings :)
from LowPassExtension to LavaDSPX
![image](https://github.com/devoxin/LavaDSPX-Plugin/assets/68145571/b7b9f238-68dd-4d6d-b88c-78cd990f9d2a)

**Comment by devoxin** [comment]
Thanks for the feedback! Although, I don't actually offer a Lyrics plugin.

I'll fix these issues ASAP. That would be the mistake of copy-pasting 😅

**Comment by Tomato6966** [comment]
Oh, Sorry I swapped you with someone else... (for the lyrics) nonetheless still thank you :3
